name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Promeni na svoj glavni branch ako nije 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout koda iz repozitorijuma
      - name: Checkout repository
        uses: actions/checkout@v3

      # Postavljanje Node.js okruženja
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Možeš promeniti verziju Node.js po potrebi

      # Instalacija zavisnosti Angular aplikacije
      - name: Install dependencies
        run: npm install

      # Instalacija Angular CLI globalno
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Bildovanje Angular aplikacije za produkciju
      - name: Build Angular App
        run: ng build --base-href "/william-clement-box/" --output-path=dist

      # Izlistavanje sadržaja dist foldera nakon build-a
      - name: List dist folder contents
        run: ls -laR dist/

      # Deploy na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/william-clement-box  # Promeni na tačan podfolder unutar dist
          publish_branch: gh-pages  # Branch za GitHub Pages
